/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DoctorView;

import java.awt.Color;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DoctorCatalogue;
import model.Patient;
import model.PatientCatalogue;
import model.VitalSign;

/**
 *
 * @author Shaiz Akhtar
 */
public class DoctorLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorLoginJPanel
     */
    
    private DoctorCatalogue doctorCatalogue;
    private PatientCatalogue patientCatalogue;
    VitalSign vitalSign;
    
    public DoctorLoginJPanel(DoctorCatalogue doctorCatalogue, PatientCatalogue patientCatalogue  ) {
        initComponents();
        this.doctorCatalogue = doctorCatalogue;
        this.patientCatalogue=patientCatalogue;
        vitalSign = new VitalSign();
        
        //Populate Doctor-dropdown
        ArrayList<String> doctorList = new ArrayList<>(); 
        doctorList.add("-- Select --");
        this.doctorCatalogue.getDoctorList().stream().forEach(action->{
            doctorList.add(action.getName());
        });
        jDoctorCombo.setModel(new DefaultComboBoxModel<>(doctorList.toArray(new String[0])));
        refreshTable();
        populateVitalTable();
        beforeLogin();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelDoctorLoginPage = new javax.swing.JPanel();
        jDoctorCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jDoctorLoginV = new javax.swing.JLabel();
        jloginBtn = new javax.swing.JButton();
        jResetBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPatientDetails = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jBodyWeightTxt = new javax.swing.JTextField();
        jHeightTxt = new javax.swing.JTextField();
        jTemperatureTxt = new javax.swing.JTextField();
        jBloodPressureTxt = new javax.swing.JTextField();
        jBtnUpdateVitals = new javax.swing.JButton();
        bwValidation = new javax.swing.JLabel();
        btValidation = new javax.swing.JLabel();
        heightValidation1 = new javax.swing.JLabel();
        bpValidation = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPInfoPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPatientAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPatientID = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jDocHospitalValidation = new javax.swing.JLabel();
        jPatientHospital = new javax.swing.JTextField();
        jPatientCity = new javax.swing.JTextField();
        jPatientName = new javax.swing.JTextField();
        jPatientCommunity = new javax.swing.JTextField();
        jPInfoPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPatientEmail = new javax.swing.JTextField();
        jDocEmailValidation = new javax.swing.JLabel();
        jAgeValidation1 = new javax.swing.JLabel();
        jGenderValidation1 = new javax.swing.JLabel();
        jLevelValidation1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPatientTelNum = new javax.swing.JTextField();
        jDocTelNumValidation = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jVitals = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jDoctorLoginName = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setMaximumSize(new java.awt.Dimension(1100, 800));
        setMinimumSize(new java.awt.Dimension(1100, 800));
        setPreferredSize(new java.awt.Dimension(1100, 800));

        jPanelDoctorLoginPage.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Doctor Login"));

        jLabel2.setText("Doctor");

        jloginBtn.setText("Login");
        jloginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginBtnActionPerformed(evt);
            }
        });

        jResetBtn.setText("Logout");
        jResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDoctorLoginPageLayout = new javax.swing.GroupLayout(jPanelDoctorLoginPage);
        jPanelDoctorLoginPage.setLayout(jPanelDoctorLoginPageLayout);
        jPanelDoctorLoginPageLayout.setHorizontalGroup(
            jPanelDoctorLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDoctorLoginPageLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(jPanelDoctorLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDoctorLoginV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDoctorCombo, 0, 137, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jloginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jResetBtn)
                .addGap(18, 18, 18))
        );
        jPanelDoctorLoginPageLayout.setVerticalGroup(
            jPanelDoctorLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDoctorLoginPageLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelDoctorLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDoctorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jloginBtn)
                    .addComponent(jResetBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDoctorLoginV, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DOCTOR VIEW");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Patient Details");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPatientDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient Id", "Patient Name", "Patient Age", "City", "Community", "Hospital"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jPatientDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPatientDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jPatientDetails);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Vital Signs"));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Body Weight");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Height");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Body Temperature");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Blood Pressure");

        jBodyWeightTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBodyWeightTxtActionPerformed(evt);
            }
        });
        jBodyWeightTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBodyWeightTxtKeyReleased(evt);
            }
        });

        jHeightTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jHeightTxtKeyReleased(evt);
            }
        });

        jTemperatureTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTemperatureTxtKeyReleased(evt);
            }
        });

        jBloodPressureTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBloodPressureTxtActionPerformed(evt);
            }
        });
        jBloodPressureTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBloodPressureTxtKeyReleased(evt);
            }
        });

        jBtnUpdateVitals.setText("Encounter");
        jBtnUpdateVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateVitalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bpValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bwValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jBodyWeightTxt)
                                .addComponent(jHeightTxt)
                                .addComponent(jTemperatureTxt)
                                .addComponent(jBloodPressureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(heightValidation1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jBtnUpdateVitals)))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jBodyWeightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(bwValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jHeightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(heightValidation1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTemperatureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(btValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jBloodPressureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(bpValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBtnUpdateVitals)
                .addGap(19, 19, 19))
        );

        jPInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Patient Information"));
        jPInfoPanel.setPreferredSize(new java.awt.Dimension(508, 276));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("PatientName");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Age");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("City");

        jPatientAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPatientAgeKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("PatientId");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Community");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Hospital");

        jDocHospitalValidation.setText("   ");

        jPatientHospital.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPatientHospitalKeyReleased(evt);
            }
        });

        jPatientCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatientCityActionPerformed(evt);
            }
        });
        jPatientCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPatientCityKeyReleased(evt);
            }
        });

        jPatientCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatientCommunityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPInfoPanelLayout = new javax.swing.GroupLayout(jPInfoPanel);
        jPInfoPanel.setLayout(jPInfoPanelLayout);
        jPInfoPanelLayout.setHorizontalGroup(
            jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDocHospitalValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPInfoPanelLayout.createSequentialGroup()
                        .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel16)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPatientCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPInfoPanelLayout.createSequentialGroup()
                                .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel4))
                                .addGap(13, 13, 13)
                                .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPatientName)
                                    .addComponent(jPatientCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPInfoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(41, 41, 41)
                                .addComponent(jPatientHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
        );
        jPInfoPanelLayout.setVerticalGroup(
            jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPInfoPanelLayout.createSequentialGroup()
                        .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPInfoPanelLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addComponent(jPatientCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPInfoPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPInfoPanelLayout.createSequentialGroup()
                        .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPInfoPanelLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPatientCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPatientHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jDocHospitalValidation)
                .addContainerGap())
        );

        jPInfoPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Contact Information"));
        jPInfoPanel1.setPreferredSize(new java.awt.Dimension(508, 276));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Email");

        jPatientEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPatientEmailKeyReleased(evt);
            }
        });

        jDocEmailValidation.setText("   ");

        jAgeValidation1.setText("   ");

        jGenderValidation1.setText("   ");

        jLevelValidation1.setText("   ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Telephone");

        jPatientTelNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatientTelNumActionPerformed(evt);
            }
        });

        jDocTelNumValidation.setText("   ");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPInfoPanel1Layout = new javax.swing.GroupLayout(jPInfoPanel1);
        jPInfoPanel1.setLayout(jPInfoPanel1Layout);
        jPInfoPanel1Layout.setHorizontalGroup(
            jPInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfoPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jAgeValidation1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPatientTelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDocTelNumValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPInfoPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(167, 167, 167)))
                .addGroup(jPInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDocEmailValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPInfoPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jGenderValidation1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLevelValidation1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPInfoPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPInfoPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPInfoPanel1Layout.setVerticalGroup(
            jPInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfoPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPInfoPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jAgeValidation1))
                    .addGroup(jPInfoPanel1Layout.createSequentialGroup()
                        .addGroup(jPInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPatientTelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDocEmailValidation)
                            .addComponent(jDocTelNumValidation))
                        .addGap(15, 15, 15)
                        .addComponent(jGenderValidation1)))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLevelValidation1))
        );

        jVitals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient Id", "Patient Name", "Body Weight", "Height", "Temperature", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jVitals);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Logged In As"));

        jDoctorLoginName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jDoctorLoginName.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jDoctorLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jDoctorLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                                    .addComponent(jPInfoPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(216, 216, 216)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelDoctorLoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(jLabel1)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDoctorLoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBodyWeightTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBodyWeightTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBodyWeightTxtActionPerformed

    private void jPatientAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPatientAgeKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jPatientAgeKeyReleased

    private void jPatientHospitalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPatientHospitalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatientHospitalKeyReleased

    private void jPatientCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPatientCityKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatientCityKeyReleased

    private void jPatientCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatientCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatientCityActionPerformed

    private void jPatientCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatientCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatientCommunityActionPerformed

    private void jPatientEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPatientEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatientEmailKeyReleased

    private void jPatientTelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatientTelNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatientTelNumActionPerformed

    private void jBloodPressureTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBloodPressureTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBloodPressureTxtActionPerformed

    private void jPatientDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPatientDetailsMouseClicked
        // TODO add your handling code here:
        int selectedRow = jPatientDetails.getSelectedRow();
        if(selectedRow<0)
        {
            return;
        }
        
        jBodyWeightTxt.setEnabled(true);
        jHeightTxt.setEnabled(true);
        jBloodPressureTxt.setEnabled(true);
        jTemperatureTxt.setEnabled(true);
        jBtnUpdateVitals.setEnabled(true);
        
        DefaultTableModel ptmodel = (DefaultTableModel) jPatientDetails.getModel();
        Patient selectedRowObj = (Patient) ptmodel.getValueAt(selectedRow, 0);
        
        //Display rowData
        jPatientID.setText(String.valueOf(selectedRowObj.getPatientId()));
        jPatientName.setText(selectedRowObj.getPatientName());
        jPatientAge.setText(String.valueOf(selectedRowObj.getPatientAge()));
        jPatientCity.setText(String.valueOf(selectedRowObj.getCity()));
        jPatientCommunity.setText(String.valueOf(selectedRowObj.getCommunity()));
        jPatientHospital.setText(String.valueOf(selectedRowObj.getHospital()));
        jPatientTelNum.setText(selectedRowObj.getPatientTelNum());
        jPatientEmail.setText(selectedRowObj.getPatientEmail()); 
    
    }//GEN-LAST:event_jPatientDetailsMouseClicked

    private void jBtnUpdateVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateVitalsActionPerformed
        // TODO add your handling code here:

        //valildations
        boolean checkIsValid = validateWeight() && validateHeight() && validateTemperature() && validatePressure();

        if(!checkIsValid){
            JOptionPane.showMessageDialog(this, "Please enter required fields!");
            return;
        }
        
        VitalSign vitalSign = new VitalSign();
        
        vitalSign.setBodyWeight(Double.parseDouble(jBodyWeightTxt.getText()));
        vitalSign.setHeight(Double.parseDouble(jHeightTxt.getText()));
        vitalSign.setTemperature(Double.parseDouble(jTemperatureTxt.getText()));
        vitalSign.setBloodPressure(jBloodPressureTxt.getText());
        populateVitalDataInPatient(vitalSign);
        populateVitalTable();
        clearFeilds();
        refreshTable();
        jBodyWeightTxt.setText("");
        jHeightTxt.setText("");
        jTemperatureTxt.setText("");
        jBloodPressureTxt.setText("");
        
        jBodyWeightTxt.setEnabled(false);
        jHeightTxt.setEnabled(false);
        jTemperatureTxt.setEnabled(false);
        jBloodPressureTxt.setEnabled(false);
        jBtnUpdateVitals.setEnabled(false);
        
    }//GEN-LAST:event_jBtnUpdateVitalsActionPerformed

    private void jBodyWeightTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBodyWeightTxtKeyReleased
        // TODO add your handling code here:
        if(!validateWeight()){
            bwValidation.setText("Weight should be in Kgs");
            bwValidation.setForeground(Color.red);
           
            
        } else {
            bwValidation.setText(" ");
        }


    
    }//GEN-LAST:event_jBodyWeightTxtKeyReleased

    private void jHeightTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jHeightTxtKeyReleased
        // TODO add your handling code here:
        if(!validateHeight()){
            heightValidation1.setText("Height should be in inches");
            heightValidation1.setForeground(Color.red);
           
        } else {
            heightValidation1.setText(" ");
        }

    }//GEN-LAST:event_jHeightTxtKeyReleased

    private void jTemperatureTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTemperatureTxtKeyReleased
        // TODO add your handling code here:
       if(!validateTemperature()){
            btValidation.setText("Please enter valid temperature");
            btValidation.setForeground(Color.red);
        } else {
            btValidation.setText(" ");
        }
 
    }//GEN-LAST:event_jTemperatureTxtKeyReleased

    private void jBloodPressureTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBloodPressureTxtKeyReleased
        // TODO add your handling code here:
//      
if(!validatePressure()){
            bpValidation.setText("Please enter sistolic and histolic bp");
            bpValidation.setForeground(Color.red);
        } else {
            bpValidation.setText(" ");
        }
 
    }//GEN-LAST:event_jBloodPressureTxtKeyReleased

    private void jloginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginBtnActionPerformed
        // TODO add your handling code here:
        if(!jDoctorCombo.getSelectedItem().toString().equals("-- Select --")){
            jDoctorLoginName.setText(jDoctorCombo.getSelectedItem().toString()); 
            afterlogin();
            refreshTable();
            populateVitalTable();
        } else {
            jDoctorLoginName.setText(" ");
            jDoctorLoginV.setText("Please Login");
            jDoctorLoginV.setForeground(Color.red);
        }
    }//GEN-LAST:event_jloginBtnActionPerformed

    private void jResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetBtnActionPerformed
        // TODO add your handling code here:
        jDoctorLoginName.setText(" ");
        jDoctorCombo.setSelectedIndex(0);
        clearFeilds();
        beforeLogin();
        clearVitalFeilds();
        refreshTable();
//        jVitals.removeAll();
        jDoctorLoginV.setText("");
        populateVitalTableOnLogout();
        
        
    }//GEN-LAST:event_jResetBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bpValidation;
    private javax.swing.JLabel btValidation;
    private javax.swing.JLabel bwValidation;
    private javax.swing.JLabel heightValidation1;
    private javax.swing.JLabel jAgeValidation1;
    private javax.swing.JTextField jBloodPressureTxt;
    private javax.swing.JTextField jBodyWeightTxt;
    private javax.swing.JButton jBtnUpdateVitals;
    private javax.swing.JLabel jDocEmailValidation;
    private javax.swing.JLabel jDocHospitalValidation;
    private javax.swing.JLabel jDocTelNumValidation;
    private javax.swing.JComboBox<String> jDoctorCombo;
    private javax.swing.JLabel jDoctorLoginName;
    private javax.swing.JLabel jDoctorLoginV;
    private javax.swing.JLabel jGenderValidation1;
    private javax.swing.JTextField jHeightTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLevelValidation1;
    private javax.swing.JPanel jPInfoPanel;
    private javax.swing.JPanel jPInfoPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelDoctorLoginPage;
    private javax.swing.JTextField jPatientAge;
    private javax.swing.JTextField jPatientCity;
    private javax.swing.JTextField jPatientCommunity;
    private javax.swing.JTable jPatientDetails;
    private javax.swing.JTextField jPatientEmail;
    private javax.swing.JTextField jPatientHospital;
    private javax.swing.JTextField jPatientID;
    private javax.swing.JTextField jPatientName;
    private javax.swing.JTextField jPatientTelNum;
    private javax.swing.JButton jResetBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTemperatureTxt;
    private javax.swing.JTable jVitals;
    private javax.swing.JButton jloginBtn;
    // End of variables declaration//GEN-END:variables

    private void beforeLogin() {
        jPatientDetails.setEnabled(false);
        jPatientID.setEnabled(false);
        jPatientName.setEnabled(false);
        jPatientAge.setEnabled(false);
        jPatientCity.setEnabled(false);
        jPatientCommunity.setEnabled(false);
        jPatientHospital.setEnabled(false);
        jPatientTelNum.setEnabled(false);
        jPatientEmail.setEnabled(false);
        jBodyWeightTxt.setEnabled(false);
        jHeightTxt.setEnabled(false);
        jBloodPressureTxt.setEnabled(false);
        jTemperatureTxt.setEnabled(false);
        jBtnUpdateVitals.setEnabled(false);
        jLabel3.setEnabled(false);
        jLabel4.setEnabled(false);
        jVitals.setEnabled(false);
        jLabel5.setEnabled(false);
        jLabel6.setEnabled(false);
        jLabel7.setEnabled(false);
        jLabel8.setEnabled(false);
        jLabel9.setEnabled(false);
        jLabel11.setEnabled(false);
        jLabel12.setEnabled(false);
        jLabel13.setEnabled(false);
        jLabel16.setEnabled(false);
        jLabel13.setEnabled(false);
        jLabel24.setEnabled(false);
        jLabel20.setEnabled(false);
        jLabel25.setEnabled(false);
        

         }

    private void afterlogin() {
        jPatientDetails.setEnabled(true);
        jPatientID.setEnabled(false);
        jPatientName.setEnabled(false);
        jPatientAge.setEnabled(false);
        jPatientCity.setEnabled(false);
        jPatientCommunity.setEnabled(false);
        jPatientHospital.setEnabled(false);
        jPatientTelNum.setEnabled(false);
        jPatientEmail.setEnabled(false);
        jBodyWeightTxt.setEnabled(false);
        jHeightTxt.setEnabled(false);
        jBloodPressureTxt.setEnabled(false);
        jTemperatureTxt.setEnabled(false);
        jBtnUpdateVitals.setEnabled(false);
        jLabel3.setEnabled(true);
        jLabel4.setEnabled(true);
        jVitals.setEnabled(true);
        jLabel5.setEnabled(true);
        jLabel6.setEnabled(true);
        jLabel7.setEnabled(true);
        jLabel8.setEnabled(true);
        jLabel9.setEnabled(true);
        jLabel11.setEnabled(true);
        jLabel12.setEnabled(true);
        jLabel13.setEnabled(true);
        jLabel16.setEnabled(true);
        jLabel13.setEnabled(true);
        jLabel24.setEnabled(true);
        jLabel20.setEnabled(true);
        jLabel25.setEnabled(true);
        
         }

    private void refreshTable() {
    DefaultTableModel dtmodel = (DefaultTableModel) jPatientDetails.getModel();
        dtmodel.setRowCount(0);
        
        
        //Populate rowData
        ArrayList<Patient>dPList = new ArrayList <Patient>();
        {
           for(Patient p:patientCatalogue.getPatientList())
           {
               if(jDoctorCombo.getSelectedItem().toString().equals(p.getConsultedDoctor()) && p.getVitalSign()==null )
               {
                   dPList.add(p);
               }
           }
        }
        for(Patient p: dPList){
                Object[] obj = new Object[6];
                obj[0] = p;
                obj[1] = p.getPatientName();
                obj[2] = p.getPatientAge();
                obj[3] = p.getCity();
                obj[4] = p.getCommunity();
                obj[5] = p.getHospital();
                dtmodel.addRow(obj);
            }
            
    }

    
    private void populateVitalDataInPatient(VitalSign vitalSign){
        for(Patient np: patientCatalogue.getPatientList())
        { 
            int id=Integer.parseInt(jPatientID.getText());
            if(np.getPatientId()==id)
            {
              np.setVitalSign(vitalSign);
            }
        }
    }
    
    private void populateVitalTable() {
        DefaultTableModel dtmodel = (DefaultTableModel) jVitals.getModel();
        dtmodel.setRowCount(0);
        //Populate rowData
        ArrayList<Patient> tempList = patientCatalogue.getPatientList(); //model-class call
            //Iterate and show data
            
            for(Patient p: tempList){
                if(p.getVitalSign()!=null && p.getConsultedDoctor().equalsIgnoreCase(jDoctorCombo.getSelectedItem().toString()))
                {
                Object[] obj = new Object[6];
                obj[0] = p;
                obj[1] = p.getPatientName();
                obj[2] = p.getVitalSign().getBodyWeight();
                obj[3] = p.getVitalSign().getHeight();
                obj[4] = p.getVitalSign().getTemperature();
                obj[5]=  p.getVitalSign().getBloodPressure();

                dtmodel.addRow(obj);
            }
            }
            
        
        }

    private void populateVitalTableOnLogout() {
        DefaultTableModel dtmodel = (DefaultTableModel) jVitals.getModel();
        dtmodel.setRowCount(0);
        //Populate rowData
        ArrayList<Patient> tempList = new ArrayList<>(); //model-class call
            //Iterate and show data
            
            for(Patient p: tempList){
                if(p.getVitalSign()!=null)
                {
                Object[] obj = new Object[6];
                obj[0] = p;
                obj[1] = p.getPatientName();
                obj[2] = p.getVitalSign().getBodyWeight();
                obj[3] = p.getVitalSign().getHeight();
                obj[4] = p.getVitalSign().getTemperature();
                obj[5]=  p.getVitalSign().getBloodPressure();

                dtmodel.addRow(obj);
            }
            }
            
        
        }

    
    
    private void clearFeilds() {
        
        jPatientID.setText("");
        jPatientName.setText("");
        jPatientAge.setText("");
        jPatientCity.setText("");
        jPatientCommunity.setText("");
        jPatientHospital.setText("");
        jPatientTelNum.setText("");
        jPatientEmail.setText("");
        jDoctorLoginV.setText(" ");
        bwValidation.setText(" ");
        heightValidation1.setText(" ");
        jDocTelNumValidation.setText(" ");
        btValidation.setText(" ");
        bpValidation.setText(" ");
        
        
        
        
        }
    
    private void clearVitalFeilds() {
        
        jBodyWeightTxt.setText("");
        jHeightTxt.setText("");
        jTemperatureTxt.setText("");
        jBloodPressureTxt.setText("");
        }
    
    
    
    private boolean validateWeight(){
        boolean isValid;
        String validWeight = jBodyWeightTxt.getText();
        Pattern pattern = Pattern.compile("^[1-9]\\d*(\\.\\d+)?$"); //Only accept > than 25
        Matcher matcher = pattern.matcher(validWeight);
        isValid = matcher.matches();
        if(isValid && Double.parseDouble(validWeight) >=2.5 && Double.parseDouble(validWeight) <=400) {
            return true;
        }
        return false;
    }
    
    private boolean validateHeight(){
        boolean isValid;
        String validWeight = jHeightTxt.getText();
        Pattern pattern = Pattern.compile("^[1-9]\\d*(\\.\\d+)?$"); //Only accept > than 25
        Matcher matcher = pattern.matcher(validWeight);
        isValid = matcher.matches();
        if(isValid && Double.parseDouble(validWeight) >=2.5 && Double.parseDouble(validWeight) <=8.5) {
            return true;
        }
        return false;
    }
    
    private boolean validateTemperature(){
        boolean isValid;
        String validWeight = jTemperatureTxt.getText();
        Pattern pattern = Pattern.compile("^[1-9]\\d*(\\.\\d+)?$"); //Only accept > than 25
        Matcher matcher = pattern.matcher(validWeight);
        isValid = matcher.matches();
        if(isValid && Double.parseDouble(validWeight) >=98.5 && Double.parseDouble(validWeight) <=105) {
            return true;
        }
        return false;
    }
    
    private boolean validatePressure(){
        boolean isValid;
        String validWeight = jBloodPressureTxt.getText();
        Pattern pattern = Pattern.compile("^(29[0-9]|2[0-9][0-9]|[01]?[0-9][0-9]?)/(29[0-9]|2[0-9][0-9]|[01]?[0-9][0-9]?)$"); //Only accept > than 25
        Matcher matcher = pattern.matcher(validWeight);
        isValid = matcher.matches();
        if(isValid) {
            return true;
        }
        return false;
    }
    


    }
