/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Employee;
import model.EmployeeCatalogue;
/**
 *
 * @author omerq
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    EmployeeCatalogue employeeCatalogue;
    
    private int empId = 1000; //Starting empId
    
    public CreateJPanel(EmployeeCatalogue employeeCatalogue) {
        initComponents();
        this.employeeCatalogue = employeeCatalogue;
        jEmpId.setEnabled(false); //non-editable
        jEmpId.setText(String.valueOf(generateEmpId()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTelNum = new javax.swing.JTextField();
        jTelNumValidation = new javax.swing.JLabel();
        jEmailValidation = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jUserPhoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jUploadPhoto = new javax.swing.JButton();
        jPInfoPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLevel = new javax.swing.JTextField();
        jPosition = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTeam = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jGender = new javax.swing.JComboBox<>();
        jStartDate = new com.toedter.calendar.JDateChooser();
        jNameValidation = new javax.swing.JLabel();
        jAgeValidation = new javax.swing.JLabel();
        jGenderValidation = new javax.swing.JLabel();
        jStartDateValidation = new javax.swing.JLabel();
        jLevelValidation = new javax.swing.JLabel();
        jTeamValidation = new javax.swing.JLabel();
        jPositionValidation = new javax.swing.JLabel();
        jAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jEmpId = new javax.swing.JTextField();
        jPictureValidation = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSaveBtn = new javax.swing.JButton();
        jClearBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 800));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Contact Information"));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Telephone");

        jEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jEmailKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Email");

        jTelNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTelNumKeyReleased(evt);
            }
        });

        jTelNumValidation.setText("   ");

        jEmailValidation.setText("   ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTelNumValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel17)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmailValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTelNum, jTelNumValidation});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jEmail, jEmailValidation});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jTelNumValidation))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEmailValidation)))
                .addGap(13, 13, 13))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Employee Picture"));

        jUserPhoto.setBackground(new java.awt.Color(255, 255, 255));
        jUserPhoto.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jUserPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jUserPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CREATE EMPLOYEE PROFILE");

        jUploadPhoto.setText("Upload");
        jUploadPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUploadPhotoActionPerformed(evt);
            }
        });

        jPInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Personal Information"));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("EmpId");

        jName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNameKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Gender");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Age");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Start Date");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Level");

        jLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLevelKeyReleased(evt);
            }
        });

        jPosition.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPositionKeyReleased(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Position");

        jTeam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTeamKeyReleased(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Team");

        jGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Male", "Female", "Others" }));
        jGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenderActionPerformed(evt);
            }
        });

        jStartDate.setDateFormatString("dd-MM-yy");
        jStartDate.setMinSelectableDate(new java.util.Date(-62135785712000L));

        jNameValidation.setText("   ");

        jAgeValidation.setText("   ");

        jGenderValidation.setText("   ");

        jStartDateValidation.setText("   ");

        jLevelValidation.setText("   ");

        jTeamValidation.setText("   ");

        jPositionValidation.setText("   ");

        jAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jAgeKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Name");

        jEmpId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jEmpIdKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPInfoPanelLayout = new javax.swing.GroupLayout(jPInfoPanel);
        jPInfoPanel.setLayout(jPInfoPanelLayout);
        jPInfoPanelLayout.setHorizontalGroup(
            jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22)
                    .addComponent(jLabel3)
                    .addComponent(jLabel16))
                .addGap(28, 28, 28)
                .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStartDateValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTeamValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAgeValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAge, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNameValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLevelValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPositionValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGenderValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGender, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPInfoPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jName, jNameValidation});

        jPInfoPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jAge, jAgeValidation});

        jPInfoPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jGender, jGenderValidation});

        jPInfoPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jStartDate, jStartDateValidation});

        jPInfoPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLevel, jLevelValidation});

        jPInfoPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTeam, jTeamValidation});

        jPInfoPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPosition, jPositionValidation});

        jPInfoPanelLayout.setVerticalGroup(
            jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPInfoPanelLayout.createSequentialGroup()
                        .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNameValidation)
                        .addGap(8, 8, 8)
                        .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgeValidation)
                    .addComponent(jGenderValidation))
                .addGap(10, 10, 10)
                .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPInfoPanelLayout.createSequentialGroup()
                        .addComponent(jStartDateValidation)
                        .addGap(10, 10, 10)
                        .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(5, 5, 5)
                        .addGroup(jPInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTeamValidation)
                            .addComponent(jPositionValidation)))
                    .addComponent(jLevelValidation))
                .addGap(14, 14, 14))
        );

        jPictureValidation.setText("   ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Action"));

        jSaveBtn.setText("Save");
        jSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveBtnActionPerformed(evt);
            }
        });

        jClearBtn.setText("Clear");
        jClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jClearBtn)
                    .addComponent(jSaveBtn))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(jUploadPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPictureValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPictureValidation)
                        .addGap(3, 3, 3)
                        .addComponent(jUploadPhoto))
                    .addComponent(jPInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearBtnActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_jClearBtnActionPerformed

    private void jUploadPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUploadPhotoActionPerformed
        //Choose Image
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showOpenDialog(null);
        File file = jFileChooser.getSelectedFile();
        if(file == null){ // If no image is selected
            jPictureValidation.setText("Please upload image!");
            jPictureValidation.setForeground(Color.red);
            return; 
        }
        String filename = file.getAbsolutePath();
        ImageIcon icon = new ImageIcon(filename);
        //Resize Image
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(167, 188, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        jUserPhoto.setIcon(scaledIcon);
        //Clear validation message
        jPictureValidation.setText(" ");
    }//GEN-LAST:event_jUploadPhotoActionPerformed

    private int generateEmpId(){
        if(!employeeCatalogue.getEmployeeList().isEmpty())
            empId = employeeCatalogue.getEmployeeList().get(employeeCatalogue.getEmployeeList().size()-1).getEmpId()+1;
        return empId;
    }
    
    private void jSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveBtnActionPerformed

        //check validations
        boolean checkIsValid = validateName() && validateAge() && validateTelNum() && validateEmail() 
                                && validatePosition() && validateLevel() && validateTeam() && !validateGender()
                                && validateImage() && validateStartDate(); 
        if(!checkIsValid){
            JOptionPane.showMessageDialog(this, "Please provide the required details!");
            return;
        }
            
        //validations passed
        Employee employee = new Employee();
        //Generate EmployeeId
        employee.setEmpId(generateEmpId());
        //Set variables
        employee.setName(jName.getText());
        employee.setAge(Integer.parseInt(jAge.getText()));
        employee.setGender(jGender.getSelectedItem().toString());
        employee.setStartDate(jStartDate.getDate());
        employee.setLevel(jLevel.getText());
        employee.setTeamInfo(jTeam.getText());
        employee.setPositionTitle(jPosition.getText());
        employee.setPhoneNumber(jTelNum.getText());
        employee.setEmail(jEmail.getText());
        employee.setEmpPhoto((ImageIcon)jUserPhoto.getIcon()); //saving ImageIcon
        
        //Add to list
        employeeCatalogue.addEmployee(employee);
        JOptionPane.showMessageDialog(this, "Employee profile " + "with empId - " + empId + " saved successfully!");
        
        //Clear fields after save
        clearFields();
    }//GEN-LAST:event_jSaveBtnActionPerformed
    
    private void clearFields(){
        //Clear fields
        jName.setText("");
        jAge.setText("");
        jGender.setSelectedIndex(0);
        jStartDate.setCalendar(null);
        jLevel.setText("");
        jTeam.setText("");
        jPosition.setText("");
        jTelNum.setText("");
        jEmail.setText("");
        jUserPhoto.setIcon(null);
        
        //Clear validation messages
        jGenderValidation.setText(" ");
        jNameValidation.setText(" ");
        jAgeValidation.setText(" ");
        jTelNumValidation.setText(" ");
        jEmailValidation.setText(" ");
        jPositionValidation.setText(" ");
        jTeamValidation.setText(" ");
        jLevelValidation.setText(" ");
        jStartDateValidation.setText(" ");
        jPictureValidation.setText(" ");
        
        //Refresh empId
        jEmpId.setText(String.valueOf(generateEmpId()));
    }

    //Validations
    private void jGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenderActionPerformed
        // TODO add your handling code here:
        if(validateGender()){
            jGenderValidation.setText("Gender Required");
            jGenderValidation.setForeground(Color.red);
        } else {
            jGenderValidation.setText(" ");
        }
    }//GEN-LAST:event_jGenderActionPerformed
 
    private boolean validateGender(){
        String selectedGender = jGender.getSelectedItem().toString();
        return selectedGender.equals("-- Select --");
    }
    
    private void jNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNameKeyReleased
        // TODO add your handling code here:
        if(!validateName()){
            jNameValidation.setText("Invalid Name");
            jNameValidation.setForeground(Color.red);
        } else {
            jNameValidation.setText(" ");
        }
    }//GEN-LAST:event_jNameKeyReleased

    private boolean validateName(){
        boolean isValid;
        String validName = jName.getText();
        Pattern pattern = Pattern.compile("[A-Za-z ]+");
        Matcher matcher = pattern.matcher(validName);
        isValid = matcher.matches();
        return isValid;
    }
    
    private void jAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAgeKeyReleased
        // TODO add your handling code here:
        if(!validateAge()){
            jAgeValidation.setText("Minimum Age 18 Required");
            jAgeValidation.setForeground(Color.red);
        } else {
            jAgeValidation.setText(" ");
        }  
    }//GEN-LAST:event_jAgeKeyReleased

    private boolean validateAge(){
        boolean isValid;
        String validAge = jAge.getText();
        Pattern pattern = Pattern.compile("[1-9]{1}[0-9]{0,1}"); //Only accept > than 18
        Matcher matcher = pattern.matcher(validAge);
        isValid = matcher.matches();
        if(isValid && Integer.parseInt(validAge) >= 18) {
            return true;
        }
        return false;
    }
    
    private void jTelNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTelNumKeyReleased
        // TODO add your handling code here:
        if(!validateTelNum()){
            jTelNumValidation.setText("Invalid Phone Number");
            jTelNumValidation.setForeground(Color.red);
        } else {
            jTelNumValidation.setText(" ");
        }  
    }//GEN-LAST:event_jTelNumKeyReleased

    private boolean validateTelNum(){
        boolean isValid;
        String validTelNum = jTelNum.getText();
        Pattern pattern = Pattern.compile("[1-9]{1}[0-9]{9}");
        Matcher matcher = pattern.matcher(validTelNum);
        isValid = matcher.matches();
        return isValid;
    }
    
    private void jEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmailKeyReleased
        // TODO add your handling code here:
        if(!validateEmail()){
            jEmailValidation.setText("Invalid Email");
            jEmailValidation.setForeground(Color.red);
        } else {
            jEmailValidation.setText(" ");
        }  
    }//GEN-LAST:event_jEmailKeyReleased

    private boolean validateEmail(){
        boolean isValid;
        String validEmail = jEmail.getText();
        Pattern pattern = Pattern.compile("[A-Za-z0-9]+[.]{0,1}[A-Za-z0-9]+[@](gmail.com|northeastern.edu)");
        Matcher matcher = pattern.matcher(validEmail);
        isValid = matcher.matches();
        return isValid;
    }
    
    private void jPositionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPositionKeyReleased
        // TODO add your handling code here:
        if(!validatePosition()){
            jPositionValidation.setText("Invalid Position Title");
            jPositionValidation.setForeground(Color.red);
        } else {
            jPositionValidation.setText(" ");
        }
    }//GEN-LAST:event_jPositionKeyReleased

    private boolean validatePosition(){
        boolean isValid;
        String validPosition = jPosition.getText();
        Pattern pattern = Pattern.compile("[A-Za-z ]+");
        Matcher matcher = pattern.matcher(validPosition);
        isValid = matcher.matches();
        return isValid;
    }
    
    private void jTeamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTeamKeyReleased
        // TODO add your handling code here: 
        if(!validateTeam()){
            jTeamValidation.setText("Invalid Team Name");
            jTeamValidation.setForeground(Color.red);
        } else {
            jTeamValidation.setText(" ");
        }
    }//GEN-LAST:event_jTeamKeyReleased

    private boolean validateTeam(){
        boolean isValid;
        String validTeam = jTeam.getText();
        Pattern pattern = Pattern.compile("[A-Za-z0-9 ]+");
        Matcher matcher = pattern.matcher(validTeam);
        isValid = matcher.matches();
        return isValid;
    }
    
    private void jLevelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLevelKeyReleased
        // TODO add your handling code here:
        if(!validateLevel()){
            jLevelValidation.setText("Invalid Level Info");
            jLevelValidation.setForeground(Color.red);
        } else {
            jLevelValidation.setText(" ");
        }
    }//GEN-LAST:event_jLevelKeyReleased

    private void jEmpIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmpIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmpIdKeyReleased

    private boolean validateLevel(){
        boolean isValid;
        String validLevel = jLevel.getText();
        Pattern pattern = Pattern.compile("[A-Za-z0-9]+");
        Matcher matcher = pattern.matcher(validLevel);
        isValid = matcher.matches();
        return isValid;
    }
    
    private boolean validateImage(){
        if(jUserPhoto.getIcon()==null) {
            jPictureValidation.setText("Please upload image!");
            jPictureValidation.setForeground(Color.red);
            return false;
        } 
        return true;
    }
    
    private boolean validateStartDate(){
        if(jStartDate.getDate()==null) {
            jStartDateValidation.setText("Joining Date Required");
            jStartDateValidation.setForeground(Color.red);
            return false;
        } 
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAge;
    private javax.swing.JLabel jAgeValidation;
    private javax.swing.JButton jClearBtn;
    private javax.swing.JTextField jEmail;
    private javax.swing.JLabel jEmailValidation;
    private javax.swing.JTextField jEmpId;
    private javax.swing.JComboBox<String> jGender;
    private javax.swing.JLabel jGenderValidation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jLevel;
    private javax.swing.JLabel jLevelValidation;
    private javax.swing.JTextField jName;
    private javax.swing.JLabel jNameValidation;
    private javax.swing.JPanel jPInfoPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jPictureValidation;
    private javax.swing.JTextField jPosition;
    private javax.swing.JLabel jPositionValidation;
    private javax.swing.JButton jSaveBtn;
    private com.toedter.calendar.JDateChooser jStartDate;
    private javax.swing.JLabel jStartDateValidation;
    private javax.swing.JTextField jTeam;
    private javax.swing.JLabel jTeamValidation;
    private javax.swing.JTextField jTelNum;
    private javax.swing.JLabel jTelNumValidation;
    private javax.swing.JButton jUploadPhoto;
    private javax.swing.JLabel jUserPhoto;
    // End of variables declaration//GEN-END:variables
}
